Show missing unit when failing in `enable_service`.

diff --git a/config/functions b/config/functions
--- a/config/functions
+++ b/config/functions
@@ -1578,7 +1578,7 @@ enable_service() {
   local target="$2"
   local target_dir=${INSTALL}
 
-  [ -f "$target_dir/$unit_dir/$unit" ] || die
+  [ -f "$target_dir/$unit_dir/$unit" ] || { echo "File not found: $target_dir/$unit_dir/$unit"; die; }
   if [ -z "$target" ] ; then
     for target in `grep '^WantedBy' $target_dir/$unit_dir/$unit | cut -f2 -d=` ; do
       if [ -n "$target" ]; then
